### ISSUE TITLE
Relevant pieces of Steve's Course

### ISSUE THREAD

**Issue by Lucas-sahn** [upkarlidder/ibmhacks#1]
Module 1 - Introduction to IBM Cloud
IBM Cloud Overview
Locations, Regions, and Zones
Account Types and Support Plans
~~Billing and Usage
Cost Estimator
IAM~~

~~Module 2 - Infrastructure (Compute, Networking, and Storage)
Virtual Servers and Bare Metal
Block and File Storage
Object Storage
Network Services
Virtual Private Cloud
VMWare~~

Module 3 - Deploying Applications
Containers and Kubernetes
OpenShift
Cloud Foundry
Cloud Functions

Module 4 - Services on IBM Cloud
Databases
Integration
Artificial Intelligence
~~Analytics
DevOps
Blockchain
Internet of Things
Cloud Paks~~

**Comment by upkarlidder** [comment]
Thanks @Lucas-sahn. Added. Let me know how it looks.

https://github.com/lidderupk/ibmhacks/blob/master/README.md#ibm-cloud-essentials-course

**Comment by upkarlidder** [comment]
Added to the readme.
